cautela.lo: /home/zend/working/php-src/ext/cautela/cautela.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/zend/working/php-src/ext/cautela $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/zend/working/php-src/ext/cautela/cautela.c -o cautela.lo 
$(phplibdir)/cautela.la: ./cautela.la
	$(LIBTOOL) --mode=install cp ./cautela.la $(phplibdir)

./cautela.la: $(shared_objects_cautela) $(CAUTELA_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_cautela) $(CAUTELA_SHARED_LIBADD)

